parameters:
#    insider_user.example.class: Insider\UserBundle\Example

services:
#    insider_user.example:
#        class: %insider_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
