Insider\UserBundle\Entity\User:
    constraints:
        - Insider\UserBundle\Validator\Constraints\UniqueLogin:
            groups: [registration]
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: 'Такой email уже используется!'
            groups: [registration]
    properties:
        promo:
            - Insider\UserBundle\Validator\Constraints\PromoExist:
                groups: [registration]
        email:
            - NotBlank:
                groups: [registration]
            - Email:
                message: 'Неверный формат email.'
                groups: [registration]
