AllBY\UserBundle\Entity\User:
    constraints:
      - Insider\UserBundle\Validator\Constraints\UniqueLogin: ~
    properties:
        email:
            - Email:
                message: 'Неверный формат email.'

FOS\UserBundle\Model\User:
    constraints:
         - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: 'Такой email уже используется!'
            groups: [InsiderRegistration]
         - Insider\UserBundle\Validator\Constraints\UniqueLogin:
             groups: [InsiderRegistration]
    properties:
        email:
            - NotBlank:
                groups: [InsiderRegistration]
            - Email:
                message: 'Неверный формат email.'
                groups: [InsiderRegistration]