imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }

framework:
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session: ~
#        save_path: "%kernel.root_dir%/var/sessions"

#        handler_id: session.handler.memcached

    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        []
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        mappings:
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Sonata Configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.block.service.text:
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_core:
    flashmessage:
        error:
            css_class: danger # optionally, a CSS class can be defined

sonata_admin:
    extensions:
        all_by_sir_trevor.admin.extension:
            admins:
                - all_by_archive.admin.archive


    title:      AllBY Admin
    options:
        use_select2: false
        pager_links: 15

    templates:
        # default global templates
#        layout:  SonataAdminBundle::layout.html.twig
    security:
            handler: sonata.admin.security.handler.role
            information:
                    EDIT: EDIT
                    LIST: LIST
                    CREATE: CREATE
                    VIEW: VIEW
                    DELETE: DELETE
                    EXPORT: EXPORT
                    OPERATOR: OPERATOR
                    MASTER: MASTER

    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
            -
                position: right
                type: sonata.block.service.text
                settings:
                    content: >
                        <h2>Добро пожаловать<br/> в систему администрирования <br/>Портала "Вся Беларусь"</h2>
                        <p>Текст приветствия или краткого руководства</p>

# FOS Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Insider\UserBundle\Entity\User
    from_email:
        address:        info@allby.tv
        sender_name:    Вся Беларусь
    registration:
        form:
            type: allby_user_registration
            validation_groups:  [AllBYRegistration]
        confirmation:
            enabled:    true
            template:   FOSUserBundle:Registration:email.txt.twig
    resetting:
        token_ttl: 60
        email:
            template:   FOSUserBundle:Resetting:email.txt.twig

#liip image bundle
liip_imagine:
    resolvers:
       default:
          web_path:
            cache_prefix: uploads/cache

    filter_sets:
        cache: ~
        ico:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }
        normal:
            filters:
              crop: { start: [10, 20], size: [120, 90] }
        block:
            quality: 100
            filters:
                thumbnail: { size: [685, 348], mode: outbound }
        rel_block:
            quality: 100
            filters:
                thumbnail: { size: [280, 150], mode: outbound }

# app/config/config.yml
knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default
# HWI oAuth Configuration

clarity_cdn:
    default: "mediaphoto"
    storage:
        mediaphoto:
            scheme: "local"
            path: "%kernel.root_dir%/../web/uploads"
            url: "http://%site_host%/uploads"
        adv:
            scheme: "local"
            path: "%kernel.root_dir%/../web/uploads"
            url: "http://%site_host%/uploads"
        user:
            scheme: "local"
            path: "%kernel.root_dir%/../web/uploads/user"
            url: "http://%site_host%/uploads/user"

sp_bower:
    install_on_warmup: true
    bundles: []
    assetic:
        enabled: false

services:
    itm.admin.twig.extension:
        class: Application\Sonata\AdminBundle\Twig\Extension\AdminExtension
        tags:
            - { name: 'twig.extension' }
