security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_ORDER_DELETE
        ROLE_CLIENT:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_ORDER_CREATE
        ROLE_ORDER_VIEW:
            - ROLE_ALL_BY_ORDER_ADMIN_ORDER_LIST
            - ROLE_ALL_BY_ORDER_ADMIN_ORDER_VIEW
        ROLE_ORDER_EDIT:
            - ROLE_ORDER_VIEW
            - ROLE_ALL_BY_ORDER_ADMIN_ORDER_EDIT
        ROLE_ORDER_CREATE:
            - ROLE_ORDER_EDIT
            - ROLE_ALL_BY_ORDER_ADMIN_ORDER_CREATE
        ROLE_ORDER_DELETE:
            - ROLE_ORDER_CREATE
            - ROLE_ALL_BY_ORDER_ADMIN_ORDER_DELETE

    access_decision_manager:
        strategy: unanimous

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                failure_handler: insider_user.authentication.handler
                success_handler: insider_user.authentication.handler
                always_use_default_target_path: true
                default_target_path: /profile
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/threads, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_SONATA_ADMIN] }
