security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CUSTOM:      [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_EDITOR:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_VIDEO_CREATE
            - ROLE_AUDIO_CREATE
            - ROLE_FLASH_CREATE
            - ROLE_PHOTO_CREATE
            - ROLE_FILE_CREATE
            - ROLE_MEDIA_CREATE
            - ROLE_CONTENT_PROJECT_CREATE
            - ROLE_ARCHIVE_CREATE
            - ROLE_RUBRICS_CREATE
            - ROLE_WIKI_CREATE
            - ROLE_MAIN_PAGE_CREATE
            - ROLE_WIKI_PAGE_CREATE
        ROLE_AUTHOR:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_VIDEO_CREATE
            - ROLE_AUDIO_CREATE
            - ROLE_FLASH_CREATE
            - ROLE_PHOTO_CREATE
            - ROLE_FILE_CREATE
            - ROLE_MEDIA_CREATE
#            - ROLE_CONTENT_PROJECT_CREATE
            - ROLE_ARCHIVE_CREATE
#            - ROLE_RUBRICS_CREATE
#            - ROLE_WIKI_CREATE
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_VIDEO_DELETE
            - ROLE_AUDIO_DELETE
            - ROLE_FLASH_DELETE
            - ROLE_PHOTO_DELETE
            - ROLE_FILE_DELETE
            - ROLE_MEDIA_DELETE
            - ROLE_CONTENT_PROJECT_DELETE
            - ROLE_ARCHIVE_DELETE
            - ROLE_RUBRICS_DELETE
            - ROLE_WIKI_DELETE
            - ROLE_API_DELETE
            - ROLE_BAN_DELETE
            - ROLE_REGISTRY_DELETE
            - ROLE_REMOVE_DELETE
            - ROLE_COMMENT_DELETE
            - ROLE_SETTINGS_DELETE
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADVERTISER:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_ADV_VIEW
        ROLE_VIDEO_VIEW:
            - ROLE_ALL_BY_VIDEO_ADMIN_VIDEO_LIST
            - ROLE_ALL_BY_VIDEO_ADMIN_VIDEO_ALBUM_LIST
            - ROLE_ALL_BY_VIDEO_ADMIN_VIDEO_VIEW
            - ROLE_ALL_BY_VIDEO_ADMIN_VIDEO_ALBUM_VIEW
        ROLE_VIDEO_EDIT:
            - ROLE_VIDEO_VIEW
            - ROLE_ALL_BY_VIDEO_ADMIN_VIDEO_EDIT
            - ROLE_ALL_BY_VIDEO_ADMIN_VIDEO_ALBUM_EDIT
        ROLE_VIDEO_CREATE:
            - ROLE_VIDEO_EDIT
            - ROLE_ALL_BY_VIDEO_ADMIN_VIDEO_CREATE
            - ROLE_ALL_BY_VIDEO_ADMIN_VIDEO_ALBUM_CREATE
        ROLE_VIDEO_DELETE:
            - ROLE_VIDEO_CREATE
            - ROLE_ALL_BY_VIDEO_ADMIN_VIDEO_DELETE
            - ROLE_ALL_BY_VIDEO_ADMIN_VIDEO_ALBUM_DELETE
        ROLE_AUDIO_VIEW:
            - ROLE_ALL_BY_AUDIO_ADMIN_AUDIO_LIST
            - ROLE_ALL_BY_AUDIO_ADMIN_AUDIO_ALBUM_LIST
            - ROLE_ALL_BY_AUDIO_ADMIN_AUDIO_VIEW
            - ROLE_ALL_BY_AUDIO_ADMIN_AUDIO_ALBUM_VIEW
        ROLE_AUDIO_EDIT:
            - ROLE_AUDIO_VIEW
            - ROLE_ALL_BY_AUDIO_ADMIN_AUDIO_EDIT
            - ROLE_ALL_BY_AUDIO_ADMIN_AUDIO_ALBUM_EDIT
        ROLE_AUDIO_CREATE:
            - ROLE_AUDIO_EDIT
            - ROLE_ALL_BY_AUDIO_ADMIN_AUDIO_CREATE
            - ROLE_ALL_BY_AUDIO_ADMIN_AUDIO_ALBUM_CREATE
        ROLE_AUDIO_DELETE:
            - ROLE_AUDIO_CREATE
            - ROLE_ALL_BY_AUDIO_ADMIN_AUDIO_DELETE
            - ROLE_ALL_BY_AUDIO_ADMIN_AUDIO_ALBUM_DELETE
        ROLE_FLASH_VIEW:
            - ROLE_ALL_BY_FLASH_ADMIN_FLASH_LIST
            - ROLE_ALL_BY_FLASH_ADMIN_FLASH_ALBUM_LIST
            - ROLE_ALL_BY_FLASH_ADMIN_FLASH_VIEW
            - ROLE_ALL_BY_FLASH_ADMIN_FLASH_ALBUM_VIEW
        ROLE_FLASH_EDIT:
            - ROLE_FLASH_VIEW
            - ROLE_ALL_BY_FLASH_ADMIN_FLASH_EDIT
            - ROLE_ALL_BY_FLASH_ADMIN_FLASH_ALBUM_EDIT
        ROLE_FLASH_CREATE:
            - ROLE_FLASH_EDIT
            - ROLE_ALL_BY_FLASH_ADMIN_FLASH_CREATE
            - ROLE_ALL_BY_FLASH_ADMIN_FLASH_ALBUM_CREATE
        ROLE_FLASH_DELETE:
            - ROLE_FLASH_CREATE
            - ROLE_ALL_BY_FLASH_ADMIN_FLASH_DELETE
            - ROLE_ALL_BY_FLASH_ADMIN_FLASH_ALBUM_DELETE
        ROLE_USER_VIEW:
            - ROLE_ALL_BY_USER_ADMIN_USER_LIST
            - ROLE_ALL_BY_USER_ADMIN_USER_VIEW
        ROLE_USER_EDIT:
            - ROLE_USER_VIEW
            - ROLE_ALL_BY_USER_ADMIN_USER_EDIT
        ROLE_USER_CREATE:
            - ROLE_USER_EDIT
            - ROLE_ALL_BY_USER_ADMIN_USER_CREATE
        ROLE_USER_DELETE:
            - ROLE_USER_CREATE
            - ROLE_ALL_BY_USER_ADMIN_USER_DELETE
        ROLE_PHOTO_VIEW:
            - ROLE_ALL_BY_PHOTO_ADMIN_PHOTO_LIST
            - ROLE_ALL_BY_PHOTO_ADMIN_PHOTO_ALBUM_LIST
            - ROLE_ALL_BY_PHOTO_ADMIN_PHOTO_VIEW
            - ROLE_ALL_BY_PHOTO_ADMIN_PHOTO_ALBUM_VIEW
        ROLE_PHOTO_EDIT:
            - ROLE_PHOTO_VIEW
            - ROLE_ALL_BY_PHOTO_ADMIN_PHOTO_EDIT
            - ROLE_ALL_BY_PHOTO_ADMIN_PHOTO_ALBUM_EDIT
        ROLE_PHOTO_CREATE:
            - ROLE_PHOTO_EDIT
            - ROLE_ALL_BY_PHOTO_ADMIN_PHOTO_CREATE
            - ROLE_ALL_BY_PHOTO_ADMIN_PHOTO_ALBUM_CREATE
        ROLE_PHOTO_DELETE:
            - ROLE_PHOTO_CREATE
            - ROLE_ALL_BY_PHOTO_ADMIN_PHOTO_DELETE
            - ROLE_ALL_BY_PHOTO_ADMIN_PHOTO_ALBUM_DELETE
        ROLE_API_VIEW:
            - ROLE_ALL_BY_API_KEY_ADMIN_API_KEY_LIST
            - ROLE_ALL_BY_API_KEY_ADMIN_API_KEY_VIEW
        ROLE_API_EDIT:
            - ROLE_API_VIEW
            - ROLE_ALL_BY_API_KEY_ADMIN_API_KEY_EDIT
        ROLE_API_CREATE:
            - ROLE_API_EDIT
            - ROLE_ALL_BY_API_KEY_ADMIN_API_KEY_CREATE
        ROLE_API_DELETE:
            - ROLE_API_CREATE
            - ROLE_ALL_BY_API_KEY_ADMIN_API_KEY_DELETE
        ROLE_BAN_VIEW:
            - ROLE_ALL_BY_BANNED_WORD_ADMIN_BANNED_WORD_LIST
            - ROLE_ALL_BY_BANNED_WORD_ADMIN_BANNED_WORD_VIEW
        ROLE_BAN_EDIT:
            - ROLE_BAN_VIEW
            - ROLE_ALL_BY_BANNED_WORD_ADMIN_BANNED_WORD_EDIT
        ROLE_BAN_CREATE:
            - ROLE_BAN_EDIT
            - ROLE_ALL_BY_BANNED_WORD_ADMIN_BANNED_WORD_CREATE
        ROLE_BAN_DELETE:
            - ROLE_BAN_CREATE
            - ROLE_ALL_BY_BANNED_WORD_ADMIN_BANNED_WORD_DELETE
        ROLE_FILE_VIEW:
            - ROLE_ALL_BY_FILE_ADMIN_FILE_LIST
            - ROLE_ALL_BY_FILE_ADMIN_FILE_CATEGORY_LIST
            - ROLE_ALL_BY_FILE_ADMIN_FILE_VIEW
            - ROLE_ALL_BY_FILE_ADMIN_FILE_CATEGORY_VIEW
        ROLE_FILE_EDIT:
            - ROLE_FILE_VIEW
            - ROLE_ALL_BY_FILE_ADMIN_FILE_EDIT
            - ROLE_ALL_BY_FILE_ADMIN_FILE_CATEGORY_EDIT
        ROLE_FILE_CREATE:
            - ROLE_FILE_EDIT
            - ROLE_ALL_BY_FILE_ADMIN_FILE_CREATE
            - ROLE_ALL_BY_FILE_ADMIN_FILE_CATEGORY_CREATE
        ROLE_FILE_DELETE:
            - ROLE_FILE_CREATE
            - ROLE_ALL_BY_FILE_ADMIN_FILE_DELETE
            - ROLE_ALL_BY_FILE_ADMIN_FILE_CATEGORY_DELETE
        ROLE_MEDIA_VIEW:
            - ROLE_ALL_BY_MEDIA_ADMIN_MEDIA_LIST
            - ROLE_ALL_BY_MEDIA_ADMIN_MEDIA_VIEW
        ROLE_MEDIA_EDIT:
            - ROLE_MEDIA_VIEW
            - ROLE_ALL_BY_MEDIA_ADMIN_MEDIA_EDIT
        ROLE_MEDIA_CREATE:
            - ROLE_MEDIA_EDIT
            - ROLE_ALL_BY_MEDIA_ADMIN_MEDIA_CREATE
        ROLE_MEDIA_DELETE:
            - ROLE_MEDIA_CREATE
            - ROLE_ALL_BY_MEDIA_ADMIN_MEDIA_DELETE
        ROLE_CONTENT_PROJECT_VIEW:
            - ROLE_ALL_BY_CONTENT_PROJECT_ADMIN_CONTENT_PROJECT_LIST
            - ROLE_ALL_BY_CONTENT_PROJECT_ADMIN_CONTENT_PROJECT_VIEW
        ROLE_CONTENT_PROJECT_EDIT:
            - ROLE_CONTENT_PROJECT_VIEW
            - ROLE_ALL_BY_CONTENT_PROJECT_ADMIN_CONTENT_PROJECT_EDIT
        ROLE_CONTENT_PROJECT_CREATE:
            - ROLE_CONTENT_PROJECT_EDIT
            - ROLE_ALL_BY_CONTENT_PROJECT_ADMIN_CONTENT_PROJECT_CREATE
        ROLE_CONTENT_PROJECT_DELETE:
            - ROLE_CONTENT_PROJECT_CREATE
            - ROLE_ALL_BY_CONTENT_PROJECT_ADMIN_CONTENT_PROJECT_DELETE
        ROLE_ARCHIVE_VIEW:
            - ROLE_ALL_BY_ARCHIVE_ADMIN_ARCHIVE_LIST
            - ROLE_ALL_BY_ARCHIVE_ADMIN_ARCHIVE_VIEW
        ROLE_ARCHIVE_EDIT:
            - ROLE_ARCHIVE_VIEW
            - ROLE_ALL_BY_ARCHIVE_ADMIN_ARCHIVE_EDIT
        ROLE_ARCHIVE_CREATE:
            - ROLE_ARCHIVE_EDIT
            - ROLE_ALL_BY_ARCHIVE_ADMIN_ARCHIVE_CREATE
        ROLE_ARCHIVE_DELETE:
            - ROLE_ARCHIVE_CREATE
            - ROLE_ALL_BY_ARCHIVE_ADMIN_ARCHIVE_DELETE
        ROLE_RUBRICS_VIEW:
            - ROLE_ALL_BY_RUBRICS_ADMIN_RUBRIC_LIST
            - ROLE_ALL_BY_RUBRICS_ADMIN_RUBRIC_VIEW
        ROLE_RUBRICS_EDIT:
            - ROLE_RUBRICS_VIEW
            - ROLE_ALL_BY_RUBRICS_ADMIN_RUBRIC_EDIT
        ROLE_RUBRICS_CREATE:
            - ROLE_RUBRICS_EDIT
            - ROLE_ALL_BY_RUBRICS_ADMIN_RUBRIC_CREATE
        ROLE_RUBRICS_DELETE:
            - ROLE_RUBRICS_CREATE
            - ROLE_ALL_BY_RUBRICS_ADMIN_RUBRIC_DELETE
        ROLE_REGISTRY_VIEW:
            - ROLE_ALL_BY_REGISTRY_ADMIN_REGISTRY_VIEW
            - ROLE_ALL_BY_REGISTRY_ADMIN_REGISTRY_LIST
        ROLE_REGISTRY_EDIT:
            - ROLE_REGISTRY_VIEW
            - ROLE_ALL_BY_REGISTRY_ADMIN_REGISTRY_EDIT
        ROLE_REGISTRY_CREATE:
            - ROLE_REGISTRY_EDIT
            - ROLE_ALL_BY_REGISTRY_ADMIN_REGISTRY_CREATE
        ROLE_REGISTRY_DELETE:
            - ROLE_REGISTRY_CREATE
            - ROLE_ALL_BY_REGISTRY_ADMIN_REGISTRY_DELETE
        ROLE_WIKI_VIEW:
            - ROLE_ALL_BY_WIKI_ADMIN_WIKI_CATEGORY_VIEW
            - ROLE_ALL_BY_WIKI_ADMIN_WIKI_CATEGORY_LIST
        ROLE_WIKI_EDIT:
            - ROLE_WIKI_VIEW
            - ROLE_ALL_BY_WIKI_ADMIN_WIKI_CATEGORY_EDIT
        ROLE_WIKI_CREATE:
            - ROLE_WIKI_EDIT
            - ROLE_ALL_BY_WIKI_ADMIN_WIKI_CATEGORY_CREATE
        ROLE_WIKI_DELETE:
            - ROLE_WIKI_CREATE
            - ROLE_ALL_BY_WIKI_ADMIN_WIKI_CATEGORY_DELETE
        ROLE_REMOVE_VIEW:
            - ROLE_ALL_BY_FOR_REMOVE_ADMIN_FOR_REMOVE_VIEW
            - ROLE_ALL_BY_FOR_REMOVE_ADMIN_FOR_REMOVE_LIST
        ROLE_REMOVE_EDIT:
            - ROLE_REMOVE_VIEW
            - ROLE_ALL_BY_FOR_REMOVE_ADMIN_FOR_REMOVE_EDIT
        ROLE_REMOVE_CREATE:
            - ROLE_REMOVE_EDIT
            - ROLE_ALL_BY_FOR_REMOVE_ADMIN_FOR_REMOVE_CREATE
        ROLE_REMOVE_DELETE:
            - ROLE_REMOVE_CREATE
            - ROLE_ALL_BY_FOR_REMOVE_ADMIN_FOR_REMOVE_DELETE
        ROLE_ADV_VIEW:
            - ROLE_ALL_BY_ADV_ADMIN_ADV_CAMPAIGN_VIEW
            - ROLE_ALL_BY_ADV_ADMIN_ADV_CONTENT_LIST
        ROLE_ADV_EDIT:
            - ROLE_ADV_VIEW
            - ROLE_ALL_BY_ADV_ADMIN_ADV_CAMPAIGN_EDIT
        ROLE_ADV_CREATE:
            - ROLE_ADV_EDIT
            - ROLE_ALL_BY_ADV_ADMIN_ADV_CAMPAIGN_CREATE
        ROLE_MAIN_PAGE_VIEW:
            - ROLE_ALL_BY_MAIN_PAGE_ADMIN_MAIN_PAGE_VIEW
            - ROLE_ALL_BY_MAIN_PAGE_ADMIN_MAIN_PAGE_LIST
        ROLE_MAIN_PAGE_EDIT:
            - ROLE_MAIN_PAGE_VIEW
            - ROLE_ALL_BY_MAIN_PAGE_ADMIN_MAIN_PAGE_EDIT
        ROLE_MAIN_PAGE_CREATE:
            - ROLE_MAIN_PAGE_EDIT
            - ROLE_ALL_BY_MAIN_PAGE_ADMIN_MAIN_PAGE_CREATE
        ROLE_WIKI_PAGE_VIEW:
            - ROLE_ALL_BY_WIKI_ADMIN_WIKI_PAGE_VIEW
            - ROLE_ALL_BY_WIKI_ADMIN_WIKI_PAGE_LIST
        ROLE_WIKI_PAGE_EDIT:
            - ROLE_WIKI_PAGE_VIEW
            - ROLE_ALL_BY_WIKI_ADMIN_WIKI_PAGE_EDIT
        ROLE_WIKI_PAGE_CREATE:
            - ROLE_WIKI_PAGE_EDIT
            - ROLE_ALL_BY_WIKI_ADMIN_WIKI_PAGE_CREATE
        ROLE_COMMENT_VIEW:
            - ROLE_ALL_BY_COMMENT_ADMIN_COMMENT_VIEW
            - ROLE_ALL_BY_COMMENT_ADMIN_COMMENT_LIST
        ROLE_COMMENT_EDIT:
            - ROLE_COMMENT_VIEW
            - ROLE_ALL_BY_COMMENT_ADMIN_COMMENT_EDIT
        ROLE_COMMENT_CREATE:
            - ROLE_COMMENT_EDIT
            - ROLE_ALL_BY_COMMENT_ADMIN_COMMENT_CREATE
        ROLE_COMMENT_DELETE:
            - ROLE_COMMENT_CREATE
            - ROLE_ALL_BY_COMMENT_ADMIN_COMMENT_DELETE
            - ROLE_ALL_BY_COMMENT_ADMIN_COMMENT_RECOVER
        ROLE_SETTINGS_VIEW:
            - ROLE_ALL_BY_SETTINGS_ADMIN_SETTINGS_VIEW
            - ROLE_ALL_BY_SETTINGS_ADMIN_SETTINGS_LIST
        ROLE_SETTINGS_EDIT:
            - ROLE_SETTINGS_VIEW
            - ROLE_ALL_BY_SETTINGS_ADMIN_SETTINGS_EDIT
        ROLE_SETTINGS_CREATE:
            - ROLE_SETTINGS_EDIT
            - ROLE_ALL_BY_SETTINGS_ADMIN_SETTINGS_CREATE
        ROLE_SETTINGS_DELETE:
            - ROLE_SETTINGS_CREATE
            - ROLE_ALL_BY_SETTINGS_ADMIN_SETTINGS_DELETE
            - ROLE_ALL_BY_SETTINGS_ADMIN_SETTINGS_RECOVER

    access_decision_manager:
        strategy: unanimous

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
#                failure_handler: all_by_user.authentication.handler
#                success_handler: all_by_user.authentication.handler
                always_use_default_target_path: true
                default_target_path: /profile
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/threads, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_SONATA_ADMIN] }
