security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_LOGOUT
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_ORDER_EXPORT
            - ROLE_COMPLETED_ORDER_DELETE
            - ROLE_DELETED_ORDER_RECOVER
            - ROLE_ORDER_CATEGORY_DELETE
            - ROLE_USER_DELETE
            - ROLE_ROLE_DELETE
            - ROLE_DELIVERY_DELETE
            - ROLE_CURRENCY_DELETE
        ROLE_CLIENT:
            - ROLE_LOGOUT
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_ORDER_DELETE
            - ROLE_COMPLETED_ORDER_DELETE
            - ROLE_DELETED_ORDER_RECOVER
            - ROLE_ORDER_CATEGORY_VIEW
            - ROLE_ALLOWED_TO_SWITCH

# USER
        ROLE_USER_VIEW:
            - ROLE_INSIDER_USER_ADMIN_USER_LIST
            - ROLE_INSIDER_USER_ADMIN_USER_VIEW
        ROLE_USER_EDIT:
            - ROLE_USER_VIEW
            - ROLE_INSIDER_USER_ADMIN_USER_EDIT
        ROLE_USER_CREATE:
            - ROLE_USER_EDIT
            - ROLE_INSIDER_USER_ADMIN_USER_CREATE
        ROLE_USER_DELETE:
            - ROLE_USER_CREATE
            - ROLE_INSIDER_USER_ADMIN_USER_DELETE
# ROLE
        ROLE_ROLE_VIEW:
            - ROLE_INSIDER_USER_ADMIN_ROLE_LIST
            - ROLE_INSIDER_USER_ADMIN_ROLE_VIEW
        ROLE_ROLE_EDIT:
            - ROLE_ROLE_VIEW
            - ROLE_INSIDER_USER_ADMIN_ROLE_EDIT
        ROLE_ROLE_CREATE:
            - ROLE_ROLE_EDIT
            - ROLE_INSIDER_USER_ADMIN_ROLE_CREATE
        ROLE_ROLE_DELETE:
            - ROLE_ROLE_CREATE
            - ROLE_INSIDER_USER_ADMIN_ROLE_DELETE
# ORDER
        ROLE_ORDER_DELETE:
            - ROLE_INSIDER_ORDER_ADMIN_ORDER_LIST
            - ROLE_INSIDER_ORDER_ADMIN_ORDER_VIEW
            - ROLE_INSIDER_ORDER_ADMIN_ORDER_EDIT
            - ROLE_INSIDER_ORDER_ADMIN_ORDER_CREATE
            - ROLE_INSIDER_ORDER_ADMIN_ORDER_DELETE
        ROLE_ORDER_EXPORT:
            - ROLE_ORDER_DELETE
            - ROLE_INSIDER_ORDER_ADMIN_ORDER_EXPORT

# DELETED ORDER
        ROLE_DELETED_ORDER_RECOVER:
            - ROLE_INSIDER_ORDER_ADMIN_DELETED_ORDER_LIST
            - ROLE_INSIDER_ORDER_ADMIN_DELETED_ORDER_VIEW
            - ROLE_INSIDER_ORDER_ADMIN_DELETED_ORDER_RECOVER

# COMPLETED ORDER
        ROLE_COMPLETED_ORDER_DELETE:
            - ROLE_INSIDER_ORDER_ADMIN_COMPLETED_ORDER_LIST
            - ROLE_INSIDER_ORDER_ADMIN_COMPLETED_ORDER_VIEW
            - ROLE_INSIDER_ORDER_ADMIN_COMPLETED_ORDER_DELETE

# DELIVERY
        ROLE_DELIVERY_DELETE:
            - ROLE_INSIDER_ORDER_ADMIN_DELIVERY_LIST
            - ROLE_INSIDER_ORDER_ADMIN_DELIVERY_VIEW
            - ROLE_INSIDER_ORDER_ADMIN_DELIVERY_CREATE
            - ROLE_INSIDER_ORDER_ADMIN_DELIVERY_DELETE

# CURRENCY
        ROLE_CURRENCY_DELETE:
            - ROLE_INSIDER_CURRENCY_ADMIN_CURRENCY_LIST
            - ROLE_INSIDER_CURRENCY_ADMIN_CURRENCY_VIEW
            - ROLE_INSIDER_CURRENCY_ADMIN_CURRENCY_CREATE
            - ROLE_INSIDER_CURRENCY_ADMIN_CURRENCY_DELETE
# ORDER CATEGORY
        ROLE_ORDER_CATEGORY_VIEW:
            - ROLE_INSIDER_ORDER_ADMIN_ORDER_CATEGORY_LIST
            - ROLE_INSIDER_ORDER_ADMIN_ORDER_CATEGORY_VIEW
        ROLE_ORDER_CATEGORY_EDIT:
            - ROLE_ORDER_CATEGORY_VIEW
            - ROLE_INSIDER_ORDER_ADMIN_ORDER_CATEGORY_EDIT
        ROLE_ORDER_CATEGORY_CREATE:
            - ROLE_ORDER_CATEGORY_EDIT
            - ROLE_INSIDER_ORDER_ADMIN_ORDER_CATEGORY_CREATE
        ROLE_ORDER_CATEGORY_DELETE:
            - ROLE_ORDER_CATEGORY_CREATE
            - ROLE_INSIDER_ORDER_ADMIN_ORDER_CATEGORY_DELETE

    access_decision_manager:
        strategy: unanimous

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                failure_handler: insider_user.authentication.handler
                success_handler: insider_user.authentication.handler
                always_use_default_target_path: true
                default_target_path: /profile
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/threads, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: [ROLE_SONATA_ADMIN] }
