services:
    application_admin.admin.extension:
        class: Application\Sonata\AdminBundle\Admin\Extension\RecoverAdminExtension
        tags:
            - { name: sonata.admin.extension, target: all_by_order.admin.order }
            - { name: sonata.admin.extension, target: all_by_user.admin.user }